name: portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc_test: ^9.1.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_table_2: ^2.3.10
  dropdown_button2: ^1.9.2
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.3.0+3
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  fluttertoast: ^8.1.2
  get_it: ^7.2.0
  image_picker: ^0.8.6+1
  internet_connection_checker_plus: ^1.0.1
  lottie: ^2.2.0
  pie_chart: ^5.3.2
  shared_preferences: ^2.0.16
  timeline_tile: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
