name: portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.3.10
  dropdown_button2: ^1.9.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  lottie: ^2.2.0
  pie_chart: ^5.3.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
